title:             Tomasz Berezowski
email:             tomberez@eti.pg.edu.pl
description:       Tomasz Berezowski Official Website
author:            Tomasz Berezowski
baseurl:           ""
url:               "https://tberezowski.github.io"

# Social Profiles
#twitter_username:  SBootstrap
github_username:   tberezowski
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
